# Generated by Django 5.2.1 on 2025-05-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('category', models.TextField(max_length=250, null=True, blank=True, default=None)),
                ('product_class', models.TextField(max_length=250, null=True, blank=True, default=None)),
                ('product_type', models.TextField(max_length=250, null=True, blank=True, default=None)),
            ],
        ),
    ]
