# Generated by Django 5.2.1 on 2025-05-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_class',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.TextField(max_length=250),
        ),
    ]
