# Generated by Django 5.2.1 on 2025-05-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_alter_products_category_alter_products_product_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_UM',
            field=models.TextField(blank=True, default='Unid.', max_length=15, null=True),
        ),
    ]
