# Generated by Django 5.2.2 on 2025-06-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, unique=True, verbose_name='Descripción')),
                ('category', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Categoría')),
                ('product_class', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Clase')),
                ('product_type', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Tipo')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario')),
                ('product_UM', models.CharField(blank=True, default='Unid.', max_length=15, null=True, verbose_name='Unidad de medida')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
        ),
    ]
