# Generated by Django 5.2.2 on 2025-06-08 18:22

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[products.models.validate_positive], verbose_name='Costo Promedio'),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_UM',
            field=models.CharField(blank=True, default='Unid.', max_length=15, null=True, verbose_name='Unidad de Medida'),
        ),
    ]
